version: '3'
services:
  pmaster:
    image: postgres:13
    container_name: pmaster
    # restart: always
    volumes:
        - ./pmaster_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - 'POSTGRES_PASSWORD=postgres'
  pstandby:
    image: postgres:13
    container_name: pstandby
    # restart: always
    volumes:
        - ./pstandby_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      - 'POSTGRES_PASSWORD=postgres'