version: '3'
services:
  database:
    image: postgres:13
    container_name: local-postgres
    restart: always
    volumes:
        - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'